# Generated by Django 5.2.3 on 2025-11-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('portfolio', models.URLField(blank=True, null=True)),
                ('role', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=1000)),
                ('degree', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('experience', models.TextField(blank=True, max_length=2000, null=True)),
                ('skills', models.TextField(max_length=1000)),
                ('projects', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
